In [1]:
import numpy as n

In [2]:
a=n.array([2,4,6])
print(a)

[2 4 6]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.max())
print(a.min())

6
2


In [5]:
b=n.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b[0]

array([1, 2, 3])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c=n.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a[1]

4

In [10]:
c[2,1]

8

In [11]:
print(c.ndim)

2


In [12]:
a2=n.ones(5)
print(a2)

[1. 1. 1. 1. 1.]


In [41]:
a3=n.empty(3)
print(a3)

[4.24399158e-314 6.36598737e-314 8.48798317e-314]


In [14]:
a4=n.arange(10)
print(a4)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a5=n.arange(10,0,-1)
print(a5)

[10  9  8  7  6  5  4  3  2  1]


In [16]:
a6=n.arange(0,10,2)
print(a6)

[0 2 4 6 8]


In [17]:
d=a.reshape(3,1)

In [18]:
print(d)
print(d.ndim)

[[2]
 [4]
 [6]]
2


In [19]:
print(a)

[2 4 6]


In [20]:
print(a.sum())

12


In [21]:
d.sum()

12

In [22]:
mat=n.array([1,2,3,4,5,6])
print(mat)

[1 2 3 4 5 6]


In [23]:
print(mat.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [24]:
print(mat.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [25]:
m=mat.reshape(2,3)
print(m)

[[1 2 3]
 [4 5 6]]


In [26]:
m.size

6

In [27]:
m.shape

(2, 3)

In [2]:
b1=n.arange(10).reshape(2,5)
print(b1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
n.resize(b1,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
b1[1,4]

9

In [32]:
a=n.array([1,2,3,4])
b=n.array([5,6,7,8])
c=a+b
print(c)
print(type(a))
print(type(b))
print(type(c))

[ 6  8 10 12]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [33]:
m1=n.array([[1,2],[3,4]])
m2=n.array([[5,6],[7,8]])
m1@m2

array([[19, 22],
       [43, 50]])

In [34]:
print(m)
n.resize(m,(3,1))

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3]])

In [35]:
print(n.sum(m,axis=0))
print(n.sum(m,axis=1))
print(n.sum(m))

[5 7 9]
[ 6 15]
21


In [36]:
print(m.mean())
print(n.mean(m))

3.5
3.5


In [37]:
print(a,b)

[1 2 3 4] [5 6 7 8]


In [53]:
print(n.concatenate((a,b),axis=0))

[1 2 3 4 5 6 7 8]


In [38]:
e=n.array([1,2,3,4,2,4])

In [40]:
print(n.unique(e))

[1 2 3 4]


In [45]:
print(n.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [44]:
f=n.array([2,4,3,1,0])
print(n.sort(f))
g=n.array([[2,6],[4,3]])
print(n.sort(g))

[0 1 2 3 4]
[[2 6]
 [3 4]]


In [46]:
f.ndim

1

In [48]:
f.shape

(5,)

In [49]:
mat

array([1, 2, 3, 4, 5, 6])

In [50]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
print(m[0:,1])

[2 5]


In [55]:
print(g[g<=4)])

[2 6 4 3]


In [54]:
g

array([[2, 6],
       [4, 3]])

In [57]:
print((g<=4)&(g%3==0))

[[False False]
 [False  True]]


In [59]:
n.nonzero(g<5)

(array([0, 1, 1], dtype=int64), array([0, 0, 1], dtype=int64))

In [64]:
f

array([2, 4, 3, 1, 0])

In [65]:
print(n.flip(f))

[0 1 3 4 2]


In [66]:
f*2

array([4, 8, 6, 2, 0])